version: "3.8"
services:
  mock-agent:
    image: "$DOCKER_REGISTRY/mock-agent:$API_VERSION"
    restart: unless-stopped
    environment:
      - MQ_HOST=host.docker.internal
      - MQ_PORT=5672
      - MQ_USERNAME="$MQ_USERNAME"
      - MQ_PASSWORD="$MQ_PASSWORD"
    # You can override the builtin replies
    #volumes:
    #  - ./mock-replies:/go/bin/mock-replies
    logging:
      driver: json-file
      options:
        max-size: "25mb"
        max-file: "2"